os:
- linux
- osx
language: java
jdk:
- openjdk11
sudo: false
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
install: skip
test: skip
jobs:
  include:
  - stage: build pull request
    if: type = pull_request
    script: "./gradlew check jacocoTestReport"
  - stage: publish master
    if: branch = master AND NOT type = pull_request AND os = linux
    script: "./gradlew publish -x test"
  - stage: build release
    if: branch =~ /release/ AND os = linux
    script: "./gradlew publish bintrayUpload -Pversion=${TRAVIS_BRANCH#'release/'}
      -x test"
  - stage: release
    if: branch =~ /release/ AND os = linux
    script: "./gradlew closeAndReleaseRepository"
  - stage: github release
    if: branch =~ /release/ AND os = linux
    script: "./scripts/github-release.sh"
env:
  global:
  - secure: cA3aG2f4BcG9KSXUGoiX2BsJuPoWOYUIVB65JK3PxwoJ+QGGXRX+jBuGA7Gbbzmo76yeEvhumcYH2A58014fAFXSkVMt/Fh9KBJcu7DfCfL1Ctc6ftYwwoaMSGl+E/c9Yi7G9jS4BnIsA2PWm2u2fZ3Wj86K2babGGTmA2i1WvNZnRp+nDZ2c24t7VLy18NmkGn6rQaD7kwg3sWzYHi47+hyeV+2bQhWD7L45m0FeYJGFkgmeDhvMEPcrvD8rqwJ6092KTZOJ7KLgoVhNhmea+oJ2M+6sketqj8FS3b8lFJoOYP+b9W5EM93gSzHiIYrkwxumdVeV41wZ0DZQo4x+9GYjD8qrDraY6nqGxl6C1afAAdBd1rYjmEYFlnipRXeGq8z/dCThx9V+Z1NA6DQKN8mho5UjWSk3xhbW6cy03XV6nAOnMfxPPrEkz0bkQfbQXSpgZQD4LQzkwi8Ib4XUZCh1HDoKmgGIpnO6Nd8BO1UzPGgJR08WG3i89jKxzmOk4T39GwMh0xDZyKcwF2Nwcecj0UeJRAYCnYuBmGAFo/kspkYw1TX+2bnl049XCXr/dMiPgYBFvP8/1MnNwFj0n/c88tdAIPq/j1OfbwyBwItX6Kz2DGBhzPcntsfDy2foS2u5kr4eqM47KaasC6T8DNhY1YLxXCirDz22d3/dq8=
  - secure: vzUJZGwMGxjGcVyiQ6/+F/KoFmZDJ+zTBLu7ljQEExropq6YBgCmEgwDX9vmJcyC/F/gPABwarc+8/ZB1qh+/Se/qbWRzrpAo4m+4N4/Kwn3lzHpZNK4dUxHpBxiH8FTiR1gyS0B/Bs7vcGnobmiY21YoEEuv1YuM/EmYK2S5GdSuMU+C/vUaEruZVIrH0iuE0aP2Z0T4DJKf6QvJYLgFfuDT2Mj9tifhmE/GJprCjntj5LrEPzn5yTPy1ynkqcj7/GEXPoCclrogWY72bJNgvgGjWbiqX9WqlttATwsaTmaSMydybDc3GuR+YBBzRXimSXhikpZRaDp5Onr/z5P41EqwB9RKJFdjykIZ1Bk6oVsn1loM8wTGMxbANVqpxZLdAc6Zk1gURl4JDsdQM5gBl6m1knjjIuEL9zp4ZxRTCoDCHBb8HvPLlBz/TjdmVSWomPR60sdvSkcCtlOc3VZF1yC6UtSG3olZwTBdVGLwGTefWUeA/c6+8L+puhLqifuq0p8ODzJELvt8obC0lhIg2BYSaG7fMskcn6DVxc/8KUaUSgkIvH6j5NXAYgu+G0cVFeZIBS0HSmwvRN/3yxACk2tOo6Cobnnd5OJwlbUVVhGs7KJNAZgHW9fYC7MjiFdEX6FhN9FYHPZeRKVhVSfz7N++gM2ZRgDn8VaUD2UmDo=
  - secure: WLH9E5bfsstTpgcNEDNjvhWndPUO4JnmzwhqNdaffRYBLyJC39lHcnGQ6DuvPK9NVDZPanGP/iqaghKikXhUecGDMkIM9kMFpG3/CYXQohvfx36l9SiJRIcgy9Bx5X5e31IOQtvelDIoFRYQISxm6dQyvNJHvY/7KLy0ndVLebEbjTJvEoGbZebYSxNhr1CmrqwnFqU+dzJgBEiFxbUbLP3Ggu3g4GSzlLvvtKfNZW5Bjkiewpsb9NI0JvjfWFgLjzZplB+17q0E6kzBRJo+jFRvx2FXmNdHEPrPq/5gHfi6R5koBP1NQWluK1AIEHtU08bWwvKXv2SsOhblHi3LyVG0mUUvLNwzFzGMFq22nZBQ76fueJdIojyj/8E9MIZ5LyDrkoO/TZYWxPeXKwwC3yhdN44c6lB7+Lpz7z1kfFH6aRnq+Nlq61DfeiE/Anvo65hVMzQW7oXNApeIrYXEAO1JZORHs8frfSUwEA2e+gXC41RdPWgL05drAn8nxAexkgouMFx5q7xWlcn8Xd690PZTfpvadPb3UIc2gwWTa7wiY7KIKlHpLKkOxhhTY9U3kFqG+RotOzI7sAQwZjK26aZrC9rhe3Q73ocv5xgZ8poRsgImOjZYrQMfslJnB7osMQIihkorZ1oHczvDyKC1KqYKhsZOZ/MzlrI7zmYmgvc=
  - secure: qUZLneDteq48nPkax3zKxF7lqWcXE1AByTS0Oi0NZ8z1Vnro2qhuDK7Bn5JC5ml9sQVsISYKrkbtiaXrxeImPEvfR44iATnSbnsYnLJZ11ICIA0oZJBXkOPA0J4Cxenri17Xd8iv5Vy7zFB0R5Bw5FtJEfI4TupN+nkMVuOjcFn5dijfjhAPPBpjKkWaIB/SIGZJbF3HRve/tlzH+bD+fSvDTASmciCJluDl5oE6HjfAtbgfihrhAWeBi92OpmW6/g5QhX4Henzrboe8W5p/6dw6tEY6awE/FPSCuFVIr2rF6d1P3L7VXlQa69+HsXRexku0e3EzShwaS99kA4uuybVn6MN5IunQeCF60IO51/Mh5sAxT/ZiFrBXtlZijX4ZhmnIqRM/HoxsNJkR5Ep5iCOtnNwDBQ/n8kSuNccS80LktnDW/QRvbN2en2Z7vLPT2JY9t0L9kM/wShFwvvVb572Iz/WcrccmxYiafKnPnzjCpgId56sMVVGUmMA2mZBrW4lIlJX5o9Slf5zEovP+XH0UvH6RWdjttyZb/0hFyjEIiXWlRF3hAQeGgRRFMNZ/vVRY2A38Hv9fTS+mUM9BGkF/iBD6K5p22j3SGbVeDEoVIDqfl52Je+0SbWoLGfXbstPFV+6+KMBaOon86yZU9/051X6vJmdHtmmlrMzU4g4=
  - secure: bYIikZNT14uB7H1N522oXfnCdAE5wY01n4/QlN4ixTbn94J6X27RFAHy1ItdMOf+RRc9xA6Y404Spd+ciK3NIcwzTryzcD+fG42RLFhid+jF4JZiv7poGR/Vj8KurzUqt6nxY/S544lN6rIM/ke9xqGsWLmlIr85AEhuLtoKxdOnN5aw2oRblPraVQK0ff8QCSbHDnh1JEq9P/pd+NXGlppaLNifnBDq6naD9leWXrJSu/CgoBxtxQJ3RfwWacpZ82zG74pfVDryeY4xwJ3d9sRqVHgoPUQbbVx2v4Bu5vV1dAeCuUZynUyaNvjLUXqNUZ9shXXK7t/G9cV2VmOlmsuAHlI+84016KXIXTGOJ5V98mho8NSBTzrjjuFbf+XpdYVD+OExIpud0V5uArOl7Ds6rIMw+LjuxVqxrev7OVyZ+WnCdfFGp8uwqGwlkam3rHTOPEn63BjqUsMA4xv1CE3vQDgVjCv20bk8vK0/J54o+vQaHwpuEvzqZT2PmsO4nRtCKSu4uQxAEVSimazgGcJBW9ucAfRPuIv/gU9vHWxH3Rr/WahYZcKDdzGUuTPSRgVr62Lic1gE42PZAPTSxJym78s7/JLYWppk9uKp8QcPIOwihkY0WbFE9IyEewoPNzWU8lhc4W2BDeQarldwfPCTWkjETLyNWByGX1B6pPE=
  - secure: FEtygx1AQq3kG/gENTs11PLIc+jXTbcOoNCIiLdYtdUVqB98qAy6jZrz6vXXUShvb0pbJBxWKy81akE+I27oYZR2sAx2OMQEEF970ke6NEbfsSpsInJsu/1CrtEVTxbSQ57P2OjTuUsZdtpBbD3e/38WiDw4D72bzCDQLoSMqfXy2fZ1hPs2KePDTDOBy5JHdZoQNpuzj5+9PTUnXto4hGKNi82AW1b6ioGqlylR0UaImfA02+PjMkwLLYy9xmSpP41vPAfXRWMTvux5XA1yGGTWi6x4wEt8hktcasnYhArz6UqcovTrGdOt+8KJ0nws4oLf+FP3Y7/1Ak7JB8jmK2pYSoQINE9Uyy4IMZpq5B22KC3u5B9KfZ7UE6P5Z2dfbYxcYXOO7UEFNJhmU1bFxfjlJV9tImylk2Zad/A4GT6LSp1eHshAg+74iIx1UxzdRhnFDYjWnPHRzYeTnHFPLk1iZjaaEuajs5kIVdjdKosPASvzK1jcLYYl8Iwyfv2dAVlWHbP6Y8SKJyXMbwMOu1clGiIRlHOI+pKqCWG4U5UMg4/rmBLydINVo3UBcsbwZx0BD58mOrynblQ+Ij0kotpQmCk/M/rpMoBRuHnPCnIdqmWk1dpJrkj1JHDHPFL0Cz6OhfzKCvb1uAqoJJd8HsUtEfLR4xF0ky3vKVnDVdc=
before_install:
- openssl aes-256-cbc -K $encrypted_79f8c2494b60_key -iv $encrypted_79f8c2494b60_iv
  -in web3j.asc.enc -out web3j.asc -d
